import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(C1827425-B401-46DF-AE93-B241AB68E355),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IFileEntry : IDispatch
{
  [id(2)] HRESULT name([out] BSTR* file_name);
  [id(3)] HRESULT extension([out] BSTR* ext_name);
  [id(4)] HRESULT permissions([out] int* perms);
  [id(5)] HRESULT type([out] int* file_type);
  [id(6)] HRESULT size([out] __int64* size_bytes);
  [id(8)] HRESULT created([out] __int64* date);
  [id(9)] HRESULT modified([out] __int64* date);
  [id(10)] HRESULT exists();

};
